name: Snyk Open Source Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Snyk Open Source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}